/** @file test_setup.cpp
 * @brief Check true-copy periodic faces, edges and corners on every split axis.
 * @details Each owned component receives a unique exactly representable integer
 * identifier. Host verification includes the whole allocated view, so stale
 * faces, edges and corners remain visible. No numerical interpolation or
 * tolerance is used: the required copy error is exactly zero.
 *
 * TODO: REVIEW. THIS TEST CODE WAS GENERATED BY AI.
 */
#include <cmath>
#include <gtest/gtest.h>
#include <limits>

#include "PeriodicSetup.h"

namespace {
    using namespace chdr::solver;

    /// Set a sentinel everywhere, then write unique global IDs on owned cells only.
    void fillOwnedIdentifiers(AJFourFieldsType& potential, ippl::Vector<int, SpatialDim> first) {
        const auto view = potential.getView();
        potential       = -1.0;
        Kokkos::parallel_for(
            "Unique global cell IDs", potential.getFieldRangePolicy(),
            KOKKOS_LAMBDA(int i, int j, int k) {
                const double id =
                    ((i + first[0] - 1) * 14 + j + first[1] - 1) * 16 + k + first[2] - 1;
                for (unsigned c = 0; c < 4; ++c)
                    view(i, j, k)[c] = 4 * id + c;
            });
    }

    /// Decode the periodic global index independently of the halo implementation.
    double cellCopyError(AJFourFieldsType::host_mirror_type host,
                         ippl::Vector<int, SpatialDim> first, int i, int j, int k) {
        const int gi = (i + first[0] - 1 + 12) % 12;
        const int gj = (j + first[1] - 1 + 14) % 14;
        const int gk = (k + first[2] - 1 + 16) % 16;
        double error = 0.0;
        for (unsigned c = 0; c < 4; ++c) {
            const double value = std::abs(host(i, j, k)[c] - (4 * ((gi * 14 + gj) * 16 + gk) + c));
            error              = std::max(
                error, std::isfinite(value) ? value : std::numeric_limits<double>::infinity());
        }
        return error;
    }

    /** @brief Inspect owned and halo cells after synchronizing the potential.
     * @details The explicit host copy is intentional: this test checks the entire
     * allocated view, whereas normal diagnostic reductions exclude ghost cells.
     * A NaN or infinity maps to an infinite error, preserving the finite guard.
     */
    double localHaloError(AJFourFieldsType& potential, ippl::Vector<int, SpatialDim> first) {
        const auto view = potential.getView();
        auto host       = potential.getHostMirror();
        Kokkos::deep_copy(host, view);
        double error = 0.0;
        for (int i = 0; i < static_cast<int>(view.extent(0)); ++i)
            for (int j = 0; j < static_cast<int>(view.extent(1)); ++j)
                for (int k = 0; k < static_cast<int>(view.extent(2)); ++k)
                    error = std::max(error, cellCopyError(host, first, i, j, k));
        return error;
    }

    void checkSplitAxis(unsigned axis) {
        auto fields = makePeriodicFieldContainer({12, 14, 16}, {1.0, 1.5, 2.0}, axis);
        checkLocalDomain(fields.getFL());
        initializeFieldStorage(fields);
        StandardSolverPeriodic solver(fields.getJ(), fields.getE(), fields.getB());
        auto& potential  = solver.A_n;
        const auto local = fields.getFL().getLocalNDIndex();
        const ippl::Vector<int, SpatialDim> first(local[0].first(), local[1].first(),
                                                  local[2].first());
        fillOwnedIdentifiers(potential, first);
        preparePotentialHalo(potential);
        double error = localHaloError(potential, first);
        MPI_Allreduce(MPI_IN_PLACE, &error, 1, MPI_DOUBLE, MPI_MAX, fields.getFL().comm);
        EXPECT_EQ(error, 0.0) << "split axis " << axis;
        EXPECT_EQ(potential.getNghost(), 1);
        EXPECT_TRUE(fields.getFL().isAllPeriodic_m);
    }

    TEST(PeriodicSetup, CopiesEveryHaloCell) {
        for (unsigned axis = 0; axis < 3; ++axis)
            checkSplitAxis(axis);
    }

    TEST(PeriodicSetup, RejectsInvalidGeometry) {
        EXPECT_THROW(makePeriodicFieldContainer({8, 8, 8}, {1, 1, 1}, 3), std::invalid_argument);
        EXPECT_THROW(makePeriodicFieldContainer({1, 8, 8}, {1, 1, 1}), std::invalid_argument);
        EXPECT_THROW(makePeriodicFieldContainer({8, 8, 8}, {1, 0, 1}), std::invalid_argument);
    }
}  // namespace
